### ISSUE TITLE
Installation on (Ubuntu based) Linux

### ISSUE THREAD

**Issue by schoening** [nut-tree/nut.js#180]
**Short summary**
I'm running into errors when trying to run `yarn run rebuild`

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed question**
I'm on Pop!_OS and have run ` yarn add -D @nut-tree/opencv-build-linux
` and `sudo apt-get install libgconf-2-4` to fix my problem.

I am getting the following error when running `yarn run rebouild`:

```
yarn run rebuild
yarn run v1.22.4
$ electron-rebuild
⠋ Building module: opencv4nodejs-prebuilt, Completed: 0gyp info find Python using Python version 3.8.6 found at "/usr/bin/python3"
⠙ Building module: opencv4nodejs-prebuilt, Completed: 0gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/username/Projects/nutjs-playground/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/username/Projects/nutjs-playground/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt/iojs-1.4.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt/iojs-1.4.13',
gyp info spawn args   '-Dnode_gyp_dir=/home/username/Projects/nutjs-playground/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt/iojs-1.4.13/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
⠼ Building module: opencv4nodejs-prebuilt, Completed: 0node:internal/fs/utils:306
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'node_modules/@nut-tree/opencv-build-linux/opencv/build/lib'
    at readdirSync (node:fs:1025:3)
    at Object.<anonymous> (/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt/lib/bundle.js:6:20)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'node_modules/@nut-tree/opencv-build-linux/opencv/build/lib'
}
gyp: Call to 'node ./lib/bundle.js' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt'.
Error: `gyp` failed with exit code: 1



Error: node-gyp failed to rebuild '/home/username/Projects/nutjs-playground/node_modules/opencv4nodejs-prebuilt'.
Error: `gyp` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (/home/username/Projects/nutjs-playground/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Rebuilder.rebuildModuleAt (/home/username/Projects/nutjs-playground/node_modules/electron-rebuild/lib/src/rebuild.js:183:9)
    at async Rebuilder.rebuild (/home/username/Projects/nutjs-playground/node_modules/electron-rebuild/lib/src/rebuild.js:145:17)
    at async /home/username/Projects/nutjs-playground/node_modules/electron-rebuild/lib/src/cli.js:145:9
error Command failed with exit code 255.
```

And when running `npx electron rebuild` directly:
```
Error launching app
Unable to find Electron app at /home/username/Projects/nutjs-playground/rebuild

Cannot find module '/home/username/Projects/nutjs-playground/rebuild'
```

Any suggestions?

**Comment by s1hofmann** [comment]
Hi @schoening,

which Electron version are you running?

Best regards

Simon

**Comment by momakes2** [comment]
Same on macOS. Electron 11.0.3

**Comment by s1hofmann** [comment]
Hi @momakes2 👋 

According to #166, Electron versions above 8 are currently not yet supported. They require additional bindings which have yet to be built

**Comment by schoening** [comment]
> Same on macOS. Electron 11.0.3

Thanks for commenting. I got busy and forgot to reply on this issue
