### ISSUE TITLE
"No matching version found"-Error when installing on Catalina

### ISSUE THREAD

**Issue by actraiser** [nut-tree/nut.js#208]
**Short summary**
When trying to install nut-js on macOS Catalina Version 10.15.7 with node v14.14.0 and electron v8.5.5 I get an "No matching version found for @nut-tree/opencv-build-darwin@undefined" error. How should I resolve this?

**Command used to install**
```
npm i @nut-tree/nut-js
```
**Output**
```
npm ERR! code 1
npm ERR! path /Users/development/project/packages/deejay/node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform darwin
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-darwin@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/.npm/_logs/2021-01-27T12_51_35_549Z-debug.log
npm ERR! child_process.js:655
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Command failed: npm install @nut-tree/opencv-build-darwin@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-darwin@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/.npm/_logs/2021-01-27T12_51_35_549Z-debug.log
npm ERR!
npm ERR!     at checkExecSyncError (child_process.js:616:11)
npm ERR!     at execSync (child_process.js:652:15)
npm ERR!     at install (/Users/development/project/packages/deejay/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (/Users/development/project/packages/deejay/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(372) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 100,  97, 114,
npm ERR!       119, 105, 110,  64,
npm ERR!       ... 272 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 51619,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(372) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 100,  97, 114,
npm ERR!     119, 105, 110,  64,
npm ERR!     ... 272 more items
npm ERR!   ]
npm ERR! }
````

Greets
-act

**Comment by actraiser** [comment]
Just out of curiosity, I installed nut.js on another Macbook with Big Sur which just went fine.  Here the installation process used  "opencv4nodejs-prebuilt@5.3.0-2" to finish the installation. Is there any known issue with Catalina?

Greets
-act

**Comment by actraiser** [comment]
Alright, after upgrading NodeJS to v14.15.4, the installation worked. I will close the issue.

Greets
-act
