### ISSUE TITLE
Unable to install nut.js

### ISSUE THREAD

**Issue by VibingCreator** [nut-tree/nut.js#245]
**Version**

1.6.0

**Short overview**

Unable to install the latest version of nut.js using npm

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

```
1087 info run opencv4nodejs-prebuilt@5.3.0-2 install node_modules/opencv4nodejs-prebuilt prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
1088 info run opencv4nodejs-prebuilt@5.3.0-2 install { code: 1, signal: null }
1089 timing reify:rollback:createSparse Completed in 401ms
1090 timing reify:rollback:retireShallow Completed in 0ms
1091 timing command:install Completed in 16945ms
1092 verbose stack Error: command failed
1092 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v16.2.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1092 verbose stack     at ChildProcess.emit (node:events:365:28)
1092 verbose stack     at maybeClose (node:internal/child_process:1067:16)
1092 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
1093 verbose pkgid opencv4nodejs-prebuilt@5.3.0-2
1094 verbose cwd /home/user/Workspace
1095 verbose Linux 5.10.42-1-MANJARO
1096 verbose argv "/home/user/.nvm/versions/node/v16.2.0/bin/node" "/home/user/.nvm/versions/node/v16.2.0/bin/npm" "install" "@nut-tree/nut-js"
1097 verbose node v16.2.0
1098 verbose npm  v7.13.0
1099 error code 1
1100 error path /home/user/Workspace/node_modules/opencv4nodejs-prebuilt
1101 error command failed
1102 error command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
1103 error Installing prebuilt OpenCV vundefined for plattform linux
1104 error npm ERR! code ETARGET
1104 error npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
1104 error npm ERR! notarget In most cases you or one of your dependencies are requesting
1104 error npm ERR! notarget a package version that doesn't exist.
1104 error
1104 error npm ERR! A complete log of this run can be found in:
1104 error npm ERR!     /home/user/.npm/_logs/2021-07-01T22_11_58_443Z-debug.log
1104 error node:child_process:747
1104 error     throw err;
1104 error     ^
1104 error
1104 error Error: Command failed: npm install @nut-tree/opencv-build-linux@undefined
1104 error npm ERR! code ETARGET
1104 error npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
1104 error npm ERR! notarget In most cases you or one of your dependencies are requesting
1104 error npm ERR! notarget a package version that doesn't exist.
1104 error
1104 error npm ERR! A complete log of this run can be found in:
1104 error npm ERR!     /home/user/.npm/_logs/2021-07-01T22_11_58_443Z-debug.log
1104 error
1104 error     at checkExecSyncError (node:child_process:707:11)
1104 error     at execSync (node:child_process:744:15)
1104 error     at install (/home/user/Workspace/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
1104 error     at Object.<anonymous> (/home/user/Workspace/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
1104 error     at Module._compile (node:internal/modules/cjs/loader:1109:14)
1104 error     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
1104 error     at Module.load (node:internal/modules/cjs/loader:989:32)
1104 error     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
1104 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
1104 error     at node:internal/main/run_main_module:17:47 {
1104 error   status: 1,
1104 error   signal: null,
1104 error   output: [
1104 error     null,
1104 error     Buffer(0) [Uint8Array] [],
1104 error     Buffer(369) [Uint8Array] [
1104 error       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
1104 error       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
1104 error       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
1104 error       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
1104 error       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
1104 error       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
1104 error       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
1104 error        99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
1104 error       117, 120,  64, 117,
1104 error       ... 269 more items
1104 error     ]
1104 error   ],
1104 error   pid: 124296,
1104 error   stdout: Buffer(0) [Uint8Array] [],
1104 error   stderr: Buffer(369) [Uint8Array] [
1104 error     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
1104 error     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
1104 error     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
1104 error     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
1104 error     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
1104 error     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
1104 error     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
1104 error      99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
1104 error     117, 120,  64, 117,
1104 error     ... 269 more items
1104 error   ]
1104 error }
1105 verbose exit 1
```

**Steps to reproduce error**

```npm install @nut-tree/nut-js```

- node: 16.2.0
- npm: 7.13.0
- platform: manjaro linux
- arch: x64
- kernel: 5.10.42-1-MANJARO x86_64

**Comment by VibingCreator** [comment]
Nut.js lacks of prebuilt binaries for the latest version of node.js environment. To solve the issue, use node environment up to v15 (snapshot release) or v14 (LTS).
