### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Sombian** [nut-tree/nut.js#250]
**Version**
1.7.0

**Short overview**
Whenever I try to call `nut.js`, following error is thrown.

```bash
indings.js?dfc1:178 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (bindings.js?dfc1:178)
    at bindings (bindings.js?dfc1:82)
    at eval (index.js?abb2:1)
    at Object../node_modules/@nut-tree/libnut-win32/index.js (renderer.js:2)
    at __webpack_require__ (renderer.js:2)
    at c (renderer.js:2)
    at eval (index.js?e1e3:1)
    at Object../node_modules/@nut-tree/libnut/index.js (renderer.js:2)
    at __webpack_require__ (renderer.js:2)
    at eval (libnut-keyboard-action.class.js?486e:3)
```

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
^

**Steps to reproduce error**
https://github.com/Any-Material/shiny-material

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by Sombian** [comment]
Fixed by install ABI 83 and declare plugins in webpack.

**Comment by Chappie74** [comment]
Hey @Sombian . Can you explain how exactly? Thanks in advance.

**Comment by Sombian** [comment]
@Chappie74 I have downgraded my `nodejs` installed and modified webpack slightly as follow.

```ts
	plugins: [
		new (require("webpack")).ExternalsPlugin("commonjs", [
			"@nut-tree/nut-js"
		]) 
	]
```

**Comment by ihewro** [comment]
I meet this error either. 
I use the vue-cli-plugin-electron-builder to build my electron app.
when I use nut.js in  main process,It generate this error

```
(node:71407) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/@nut-tree/libnut-darwin/index.js?:1:90)
    at Object../node_modules/@nut-tree/libnut-darwin/index.js (/Users/*/Documents/personal/life/dist_electron/index.js:898:1)
    at __webpack_require__ (/Users/*/Documents/personal/life/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/@nut-tree/libnut/index.js?:8:11)
    at eval (webpack:///./node_modules/@nut-tree/libnut/index.js?:10:3)
    at Object../node_modules/@nut-tree/libnut/index.js (/Users/*/Documents/personal/life/dist_electron/index.js:931:1)
    at __webpack_require__ (/Users/*/Documents/personal/life/dist_electron/index.js:20:30)

```
