### ISSUE TITLE
Docker run issue: opencv4nodejs.node: invalid ELF header

### ISSUE THREAD

**Issue by amsdak15** [nut-tree/nut.js#289]
**Desired execution environment / tested on**
- [ ] Docker container

When an image is built with npm install @nut-tree/nut-js, the following error occurs when running the docker container. What can be the issue here?  This problem does not occur on local testing

Error: /app/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/opencv4nodejs-prebuilt/lib/cv.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! project_name@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the project_name@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Thanks in advance.

**Comment by s1hofmann** [comment]
Could you please provide your `Dockerfile`?
