### ISSUE TITLE
Install nut.js

### ISSUE THREAD

**Issue by richmailYT** [nut-tree/nut.js#314]
Error installing nut.js

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/richmail/Document/AutoClicker-NodeJS/node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform darwin
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-darwin@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/richmail/.npm/_logs/2021-11-21T00_54_39_582Z-debug.log
npm ERR! node:child_process:903
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: npm install --no-save @nut-tree/opencv-build-darwin@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-darwin@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/richmail/.npm/_logs/2021-11-21T00_54_39_582Z-debug.log
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:826:11)
npm ERR!     at execSync (node:child_process:900:15)
npm ERR!     at install (/Users/richmail/Document/AutoClicker-NodeJS/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (/Users/richmail/Document/AutoClicker-NodeJS/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1097:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:975:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(375) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 100,  97, 114,
npm ERR!       119, 105, 110,  64,
npm ERR!       ... 275 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 1044,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(375) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 100,  97, 114,
npm ERR!     119, 105, 110,  64,
npm ERR!     ... 275 more items
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v17.1.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richmail/.npm/_logs/2021-11-21T00_54_39_832Z-debug.log```

**Comment by s1hofmann** [comment]
node 17 is currently not supported by nut.js. If possible, try using latest lts (node 16, a.k.a. `lts/gallium`)
