### ISSUE TITLE
Install fails on Windows 2022

### ISSUE THREAD

**Issue by kokarn** [nut-tree/nut.js#328]
**Version**
Latest

**Short overview**
Install fails because of a missing dependency it seems like

**Issue occurs on**
- [X] Virtual machine
- [X] Dev/Host system

**Detailed error description**
```
npm ERR! code 1
npm ERR! path C:\repos\my-project\node_modules\opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform win32
npm ERR! prebuild-install WARN install The specified module could not be found.
npm ERR! prebuild-install WARN install \\?\C:\repos\my-project\node_modules\opencv4nodejs-prebuilt\build\Release\opencv4nodejs.node
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
```

**Steps to reproduce error**
`npm i @nut-tree/nut-js`

**Additional content**

```
PS C:\repos\my-project> npm i @nut-tree/nut-js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\repos\my-project\node_modules\opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform win32
npm ERR! prebuild-install WARN install The specified module could not be found.
npm ERR! prebuild-install WARN install \\?\C:\repos\my-project\node_modules\opencv4nodejs-prebuilt\build\Release\opencv4nodejs.node
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\oskar.risberg\AppData\Local\npm-cache\_logs\2021-11-30T09_00_32_560Z-debug.log
npm ERR! node:child_process:903
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: Command failed: npm install --no-save @nut-tree/opencv-build-win32@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-win32@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\oskar.risberg\AppData\Local\npm-cache\_logs\2021-11-30T09_00_32_560Z-debug.log
npm ERR!
npm ERR!     at checkExecSyncError (node:child_process:826:11)
npm ERR!     at execSync (node:child_process:900:15)
npm ERR!     at install (C:\repos\my-project\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (C:\repos\my-project\node_modules\opencv4nodejs-prebuilt\install\dependencies.js:26:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1101:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(400) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!        51,  50,  64, 117,
npm ERR!       ... 300 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 9000,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(400) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 119, 105, 110,
npm ERR!      51,  50,  64, 117,
npm ERR!     ... 300 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oskar.risberg\AppData\Local\npm-cache\_logs\2021-11-30T09_00_40_644Z-debug.log```

**Comment by s1hofmann** [comment]
Hi @kokarn 👋 

Which version of node/Electron are you using?

**Comment by kokarn** [comment]
I'm on node 16.13.0

**Comment by s1hofmann** [comment]
Continued in #358
