### ISSUE TITLE
Invalid file signature error when using get-pixels with screen.grab

### ISSUE THREAD

**Issue by KolbySisk** [nut-tree/nut.js#378]
I'm utilizing [get-pixels](https://github.com/scijs/get-pixels) in my project, and I want to give it a Buffer. When I do though, I get this error:

`Error: Invalid file signature`

Here is my code:

``` js
const screenCapture = await screen.grabRegion(region);
getPixels(screenCapture.data, 'image/png', async (error, pixels)
```

This works fine when saving an image using screen.capture and passing the url, and worked fine when using robot.js. Any advice to get this working?

Thanks.

**Comment by KolbySisk** [comment]
I've also tried converting to RGB and received the same error.

```js
const screenCapture = await screen.grabRegion(region);
const image = await screenCapture.toRGB();
getPixels(image.data, 'image/png', async (error, pixels)
```

If I use mimetype `image/jpg` I get this error: `Error: SOI not found`. Researching the error didn't bring back much.

**Comment by s1hofmann** [comment]
Hi @KolbySisk 👋 

Could you please share the mentioned working robotjs snippet?
Buffer data is identical in both cases and my quick test with robotjs ran into the exact same error.

```js
const { screen } = require("@nut-tree/nut-js");
const getPixels = require("get-pixels");
const robot = require("robotjs");

(async () => {
  const robotResult = robot.screen.capture();
  console.log(robotResult);
  const result = await screen.grab();
  console.log(result);
  getPixels(robotResult.image, 'image/png', async (error, pixels) => {
      console.log(error, pixels)
    });
})();
```

```bash
bitmap {
  width: 1920,
  height: 1080,
  byteWidth: 7680,
  bitsPerPixel: 32,
  bytesPerPixel: 4,
  image: <Buffer d5 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d5 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f6 ff d5 87 f5 ff d4 87 ... 8294350 more bytes>,
  colorAt: [Function (anonymous)]
}
Image {
  width: 1920,
  height: 1080,
  data: <Buffer d5 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d5 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f5 ff d4 86 f6 ff d5 87 f5 ff d4 87 ... 8294350 more bytes>,
  channels: 4,
  id: 'grabScreenResult',
  colorMode: 0,
  pixelDensity: { scaleX: 1, scaleY: 1 }
}
Error: Invalid file signature
    at module.exports.Parser._parseSignature (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/parser.js:53:18)
    at module.exports.ChunkStream._processRead (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/chunkstream.js:61:8)
    at module.exports.ChunkStream.end (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/chunkstream.js:74:10)
    at exports.PNG.PNG.end (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/png.js:98:16)
    at exports.PNG.PNG.parse (/private/tmp/o/node_modules/get-pixels/node_modules/pngjs/lib/png.js:88:8)
    at handlePNG (/private/tmp/o/node_modules/get-pixels/node-pixels.js:17:7)
    at doParse (/private/tmp/o/node_modules/get-pixels/node-pixels.js:109:7)
    at getPixels (/private/tmp/o/node_modules/get-pixels/node-pixels.js:140:5) undefined
```

**Comment by KolbySisk** [comment]
I must have been mistaken about Robotjs working. I wasn't able to reproduce it. I'll open an issue with get-pixels instead. Thanks for looking into it Simon.

**Comment by s1hofmann** [comment]
You're welcome, @KolbySisk

Gonna close this issue then.
