### ISSUE TITLE
Electron + Windows 7

### ISSUE THREAD

**Issue by MaikonPanazzolo** [nut-tree/nut.js#397]
**2.0.1**

**Short overview**

I'm using ElectronJS version 18.0.3 and running in my computer with Windows 11 and before 10 works fine but when I try to run
in my gf's notebook I got an error, and I have installed the necessary packages as mentioned in another issue ( #126  ) but still the same.

**Issue occurs on**
- [ x] Virtual machine
- [ ] Docker container
- [ x] Dev/Host system

**Detailed error description**

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: The specified procedure could not be found.
\\?\C:\Users\Teste\Desktop\win-unpacked\resources\app\node_modules\@nut-tree\libnut-win32\build\Release\libnut.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (C:\Users\Teste\Desktop\win-unpacked\resources\app\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\Teste\Desktop\win-unpacked\resources\app\node_modules\@nut-tree\libnut-win32\index.js:1:35)

[OK]

**Steps to reproduce error**

Just run any Electron app with the package installed

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @MaikonPanazzolo 👋 

Windows 7 is [EOL](https://docs.microsoft.com/en-us/lifecycle/products/windows-7) and not considered for support.

If you want to get support on this, feel free to reach out to via my GH contact mail.

**Comment by MaikonPanazzolo** [comment]
Apparently, I found the problem, the package is using a function that only exists from windows 10 forward:

SetThreadDpiAwarenessContext - screengrab.c

![image](https://user-images.githubusercontent.com/32369765/165403554-7569c524-2ad5-4cdf-8ac0-e0839692712b.png)
