### ISSUE TITLE
Docker issue, Unsupported Relocation Type

### ISSUE THREAD

**Issue by thomasefbland** [nut-tree/nut.js#427]
nut-js v2.2.0
node v16.16.0

**Short overview**
Trying to launch the example project in linux alpine docker container on my M1 Macbook Pro. It functions as expected outside of the container, but inside throws a strange error.

**Issue occurs on**
- [ ] Virtual machine
- [x] Docker container
- [ ] Dev/Host system

**Detailed error description**
Dockerfile
```
FROM node:16-alpine3.15
RUN apk add build-base libxtst-dev
WORKDIR /src
COPY package.json /src
RUN npm install
COPY . /src
CMD ["npm", "start"]
```
index.js
```javascript
"use strict";

const { mouse, left, right, up, down, straightTo, centerOf, Region} = require("@nut-tree/nut-js");

const square = async () => {
  await mouse.move(right(500));
  await mouse.move(down(500));
  await mouse.move(left(500));
  await mouse.move(up(500));
};

(async () => {
    await square();
    await mouse.move(
        straightTo(
            centerOf(
                new Region(100, 100, 200, 300)
            )
        )
    );
})();
```
Error thrown in the Docker container. Runs successfully outside Docker. There are no additional dependencies/packages manually installed other than nut-js
```
/src/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error relocating /src/node_modules/@nut-tree/libnut-linux/build/Release/libnut.node: unsupported relocation type 7
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1210:18)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/src/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/src/node_modules/@nut-tree/libnut-linux/index.js:1:35)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Steps to reproduce error**
Build a docker image with the dockerfile and index script, run the container

**Comment by s1hofmann** [comment]
Hi @thomasefbland 👋 

I just tried to reproduce your reported issue, but my the image I built following your provided `Dockerfile` does not throw said error.

**Comment by praser** [comment]
I have the same scenario here. I can run it locally in my M1 Pro Macbook, but when I try it in an Alpine Docker container I get this error:

```
/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error relocating /app/node_modules/@nut-tree/libnut-linux/build/Release/libnut.node: unsupported relocation type 7
    at Module._extensions..node (node:internal/modules/cjs/loader:1465:18)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/@nut-tree/libnut-linux/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.12.1
```

Maybe something to do with docker containers running over Apple Silicon?

**Comment by praser** [comment]
I have confirmed that it has to be with arm64 architecture. The error does not happen when running the container with --platform linux/amd64.

**Comment by codebanesr** [comment]
yeah, i can confirm too. You need to enable mac virtualization and then use platform linux/amd64, then it works fine
