### ISSUE TITLE
Cannot code sign when using nut-js with electron-rebuild

### ISSUE THREAD

**Issue by nnguyen01** [nut-tree/nut.js#519]
**Version**
3.1.2

**Short overview**

Was using nut.js on my application and noticed that code signing broke when migrating to electron-rebuild.

https://github.com/electron-userland/electron-builder/issues/7655

^ Tracking the issue here but curious if there are any issues in this package.

cc: @s1hofmann 

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

```SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign: C:\dev\project\release\build\win-unpacked\resources\app.asar.unpacked\node_modules\@nut-tree\libnut-darwin\build\Release\libnut.node

    at C:\dev\project\node_modules\builder-util\src\util.ts:133:18
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
From previous event:
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at WinPackager.signApp (C:\dev\project\node_modules\app-builder-lib\src\winPackager.ts:407:27)
    at WinPackager.doSignAfterPack (C:\dev\project\node_modules\app-builder-lib\src\platformPackager.ts:332:21)
    at WinPackager.doPack (C:\dev\project\node_modules\app-builder-lib\src\platformPackager.ts:317:7)
    at WinPackager.pack (C\dev\project\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (C:\dev\project\node_modules\app-builder-lib\src\packager.ts:442:9)
    at executeFinally (C\dev\project\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (C:\dev\project\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (C:\dev\project\node_modules\app-builder-lib\src\packager.ts:337:12)
    at executeFinally (C:\dev\project\node_modules\builder-util\src\promise.ts:12:14)
```

**Steps to reproduce error**

To reproduce add https://github.com/nut-tree/nut.js as a native dependency to an electron project and try code signing with v24.0.0-alpha.1 vs v23.6.0. (electron-rebuild vs not with electron-rebuild

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
@nnguyen01 The linked issue has been closed as resolved, so I’ll go ahead and close this over as well.
Thanks for bringing it up!
